erehwon/erehwon/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView

from core.views import HomepageView

from profiles.views import MyActivationView, logout_view, project_add,user_page, idea_add, project_update, idea_list, call_list
from profiles.forms import ErehwonUserSignUpForm
from registration.backends.hmac.views import RegistrationView

from messagesApp.views import MessagesProfileView, MessagesIndexView, MessagesWidgetView
import notifications.urls

import postman.urls
from messagesApp.views import api_send_message, api_get_conversation, api_get_correspondents

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^search/', include( 'ajaxsearch.urls' ) ),
    url(r'^accounts/register/$', RegistrationView.as_view(form_class=ErehwonUserSignUpForm), name="registration_register"),
    url(r'^accounts/activate/$', MyActivationView.as_view, name='activation'),
    url(r'^accounts/', include('registration.backends.hmac.urls')), # This line includes automatically all views and urls for registration/activation/password reset
    url(r'^accounts/login$', auth_views.login, name='login'),   
    url(r'^$', HomepageView.as_view(), name="index"),
    url(r'^accounts/logout/$', logout_view, name="logout"), # {'next_page': 'homepage'}, name="logout"),
    url(r'^home/$', user_page, name="user_page"),
    url(r'^home/addproject/$', project_add, name="project_add"),
    url(r'^home/add-ideas/$', idea_add, name="idea_add"),
    url(r'^ideas/$', idea_list, name="idea_list"),
    url(r'^calls/$', call_list, name="call_list"),

    # django-postman
    url(r'^messages/erehwon/$', MessagesIndexView.as_view(), name='MessagesIndex View'),
    url(r'^messages/messageprofile/$', MessagesProfileView.as_view(), name='MessagesProfile View'),
    url(r'^messages/widget/$', MessagesWidgetView, name='Messages Widget View'),

    #TODO write some custom postman views
    #css classes here: http://django-postman.readthedocs.io/en/latest/views.html
    #and hook them up.
    url(r'^inbox/$', TemplateView.as_view(template_name='inbox.html')),
    url(r'^messages/', include('postman.urls', namespace='postman', app_name='postman')),
    # django-notifications-hq
    url(r'^inbox/notifications/', include(notifications.urls, namespace='notifications')),
    url(r'^api/sendmessage/$', api_send_message, name='Api Send Message View'),
    url(r'^api/get_conversation/$', api_get_conversation, name='Api Get Conversation View'),
    url(r'^api/messages/$', api_get_conversation, name='API Get Messages'),
    url(r'^api/correspondents/$', api_get_correspondents, name='API Get Correspondents'),
]

erehwon/messagesApp/models.py
from django.db import models

# Create your models here.
from django.views.generic import TemplateView

# from http://m-x.io/blog/how-to-use-django-postman-with-django-notifications/

"""Handle notification signals from django-postman and pass
them to django-notifications. Postman does not """

# In the app's models.py:

from django.contrib.auth.models import User

from notifications.signals import notify

#User = profiles.ErehwonUser
from django.contrib.auth import get_user_model
def send(users=[], label='', extra_context={}):
    print("send fired")

    if label == 'postman_message':
        print("send in pm fired")
        msg = extra_context['pm_message']
        User = get_user_model()
        user = User.objects.get(pk=msg.sender_id)
        notify.send(user, recipient=users[0], verb='New message', description=msg.subject)

#due to bug in django postman management.py, include the schema for unrelated package here:
from django.utils.translation import ugettext_lazy as _
class NoticeType(models.Model):

    label = models.CharField(_("label"), max_length=40)
    display = models.CharField(_("display"), max_length=50)
    description = models.CharField(_("description"), max_length=100)

    # by default only on for media with sensitivity less than or equal to this number
    default = models.IntegerField(_("default"))

    def __str__(self):
        return self.label

    class Meta:
        verbose_name = _("notice type")
        verbose_name_plural = _("notice types")

    @classmethod
    def create(cls, label, display, description, default=2, verbosity=1):
        """
        Creates a new NoticeType.
        This is intended to be used by other apps as a post_syncdb manangement step.
        """
        try:
            notice_type = cls._default_manager.get(label=label)
            updated = False
            if display != notice_type.display:
                notice_type.display = display
                updated = True
            if description != notice_type.description:
                notice_type.description = description
                updated = True
            if default != notice_type.default:
                notice_type.default = default
                updated = True
            if updated:
                notice_type.save()
                if verbosity > 1:
                    print("Updated %s NoticeType" % label)
        except cls.DoesNotExist:
            cls(label=label, display=display, description=description, default=default).save()
            if verbosity > 1:
                print("Created %s NoticeType" % label)

erehwon/profiles/models.py
from django.db import models
from django.utils import timezone

from custom_user.models import AbstractEmailUser

class ErehwonUser(AbstractEmailUser):
#
#     # basic information
  username = models.CharField(max_length=30, blank=True)

  def __str__(self):
        return self.username

class Project(models.Model):

   user = models.ForeignKey(ErehwonUser)
   title = models.CharField(max_length=30)
   synopsis = models.TextField(max_length=300)
   material = models.URLField(max_length=300, blank=True)
   contributors = models.CharField(max_length=20)
   active_status = models.BooleanField(default=1)
   is_added_to_map = models.BooleanField(default=0)

   def __str__(self):
       return self.title

class Idea(models.Model):

    user = models.ForeignKey(ErehwonUser)
    project = models.ForeignKey('profiles.Project')
    title = models.CharField(max_length=30)
    synopsis = models.TextField(max_length=300)
    contributors = models.CharField(max_length=20)

    def __str__(self):
        return self.title


class CallForAction(models.Model):

    user = models.ForeignKey(ErehwonUser)
    title = models.CharField(max_length=30)
    synopsis = models.TextField(max_length=300, default='Synopsis')
    action_location = models.CharField(max_length=30, default='Erehwon')
    date = models.DateTimeField(db_index=True, default=timezone.now)
    contributors = models.CharField(max_length=20, default='Erehwon')

    def __str__(self):
        return self.title


from django.dispatch import receiver
from registration.signals import user_activated
from django.contrib.auth import login

@receiver(user_activated)
def login_on_activation(sender, user, request, **kwargs):
    """Logs in the user after activation"""
    user.backend = 'django.contrib.auth.backends.ModelBackend'
    login(request, user)

erehwon/profiles/forms.py
from django import forms
from profiles.models import Project
from profiles.models import ErehwonUser
from profiles.models import Idea

from django.db.models import ImageField

from registration.forms import RegistrationForm


class ErehwonUserSignUpForm(RegistrationForm):

    class Meta:
        model = ErehwonUser
        fields = ('email', 'password1', 'password2', 'username')


class ProjectForm(forms.ModelForm):
    file_field = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))
    class Meta:
        model = Project
        fields = ('user', 'title', 'synopsis', 'image' )


class IdeaForm(forms.ModelForm):

	class Meta:
		model = Idea
		fields = ('user', 'project', 'title', 'synopsis', 'contributors')

erehwon/profiles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse, HttpResponseForbidden
from django.core.urlresolvers import reverse
from django.views.generic import TemplateView
from django.views.generic.edit import FormView, UpdateView
from django.contrib.auth import logout
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
import logging
from registration.signals import user_registered

from registration.backends.hmac import views as registration_views
from registration.backends.hmac.views import ActivationView

from profiles.models import Project, Idea, CallForAction
from profiles.forms import ProjectForm
from profiles.forms import IdeaForm

log = logging.getLogger("erehwon")




class MyActivationView(ActivationView):

    def get_success_url(self, request, user):
        return redirect('/home', permanent=True)


def logout_view(request):
    logout(request)

    return redirect('/', permanent=True)


@login_required
def user_page(request):

    return render(request, 'profiles/my-projects.html')


@login_required
def project_update(request, project_id):

    project = get_object_or_404(Project, pk=project_id)
    # if project.user != request.user:
    #     return HttpResponseForbidden()

    project_update_form = ProjectForm(initial={'title':project.title, 'synopsis':project.synopsis})

    if request.method == 'POST':
        project_update_form = ProjectForm(request.POST, instance=request.project)
        if project_update_form.is_valid():
            project_details = project_update_form.save(commit=False)
            project_details.save(update_fields=['title', 'synopsis', 'is_added_to_map'])
            project_update_form.save_m2m()
            return redirect('/projects')
    else:
        project_update_form = ProjectForm()

    context = {'project_update_form': project_update_form}

    return render(request, 'profiles/project.html', context)


@login_required
def project_add(request):

    if request.method == 'POST':
        new_project_form = ProjectForm(request.POST)
        if new_project_form.is_valid():
            new_project_form.save()
            return HttpResponseRedirect(reverse('user_page'))

    else:
        new_project_form = ProjectForm()

    context = {'new_project_form': new_project_form}

    return render(request, 'profiles/project.html', context)


@login_required
def idea_add(request):

    if request.method == 'POST':
        new_idea_form = IdeaForm(request.POST)
        if new_idea_form.is_valid():
            new_idea_form.save()
            return HttpResponseRedirect(reverse('user_page'))

    else:
        new_idea_form = IdeaForm()

    context = {'new_idea_form': new_idea_form}

    return render(request, 'profiles/add-ideas.html', context)


@login_required
def idea_list(request):

	ideas = Idea.objects.filter(user=request.user)
	context = {'ideas': ideas}

	return render(request, 'profiles/ideas.html', context)

@login_required
def call_list(request):

    calls = CallForAction.objects.filter(user=request.user)
    context = {'calls': calls}

    return render(request, 'profiles/callforaction.html', context)

erehwon/erehwon/templates/profiles/add-ideas.html
{% extends "dashboard-layout.html" %}
{% load static %}

{% block main %}
<h1> Add/Edit Idea </h1>
	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
		<form action="" method="post">
			{% csrf_token %}
			{{ new_idea_form.as_p }}
			<input type="submit" class="submit" value="Submit">
		</form>
{% endblock %}

erehwon/erehwon/templates/profiles/callforaction.html
{% extends "dashboard-layout.html" %}

{% load static %}

{% block main %}
<section class="idea" ng-controller="ManageController">
    <div class="add-idea">
        <button href="#" class="button-primary add-idea_button" ng-click="clickAdd()">  <span class="idea-icon__add">+</span> Add new Call for action
        </button>
        <div class="add-idea_wrap" ng-show="showAdd">
            <form class="new_idea__form">
                <input type="text" placeholder="Title">
                <textarea placeholder="Synopsis" maxlength="100" rows="3"></textarea>
                <select name="select">
                    <option value="" disabled selected>Select a label</option>
                    <option value="value1">Digital Activism</option>
                    <option value="value2">Activism</option>
                    <option value="value3">Community Development</option>
                    <option value="value3">Urban Planning</option>
                    <option value="value3">New Ecologies</option>
                    <option value="value3">Alternative Economies</option>
                    <option value="value3">Citizen Movements</option>
                    <option value="value3">Artistic Interventions</option>
                </select>
                <input type="text" class="tagged" name="tag-1" data-removeBtn="true" placeholder="create a tag">
                <input type="text" placeholder="Location">
                <input type="text" placeholder="Time">
                <input type="text" placeholder="Contributors">
            </form>
            <button class="button">Add</button>
        </div>
    </div>
</section>
<section>
    <h1> My Calls for Action </h1>
    <ul class="idea-list">
        {% for call in calls %}
        <li>
            <div class="idea-info idea-list-col">
                <a href="#"><h2>{{ call.title }}</h2></a>
                <div>
                    <p>Contributors: 2</p>
                    <!-- <ul>
                        <li>{{ call.get_label_display }}</li>
                    </ul> -->
                </div>
            </div>
            <button class="button idea-list-col edit-button">Edit</button>
            <!-- <a href="#" class="idea-list-col">Add to map</a>
            <a href="#" class="idea-list-col">Remove from map</a> -->
        </li>
        {% endfor %}

    </ul>
</section>
{% endblock %}

erehwon/erehwon/templates/profiles/dashboard-logged-in.html
{% extends "dashboard-layout.html" %}

{% load static %}


    {% block main %}
    <section class="motd">
        <h2>HOMEPAGE</h2>
    </section>

    {% endblock %}

erehwon/erehwon/templates/profiles/ideas.html
{% extends "dashboard-layout.html" %}

{% load static %}

{% block main %}
<section class="idea" ng-controller="ManageController">
    <div class="add-idea">
        <button href="#" class="button-primary add-idea_button" ng-click="clickAdd()">  <span class="idea-icon__add">+</span> Add an idea
        </button>
        <div class="add-idea_wrap" ng-show="showAdd">
            <div class="img-circle"></div>
            <form class="new_idea__form">
                <input type="text" placeholder="Title">
                <textarea placeholder="Synopsis" maxlength="100" rows="3"></textarea>
                <input type="text" class="tagged" name="tag-1" data-removeBtn="true" placeholder="create a tag">
                <input type="text" placeholder="Invite People">
                <input type="text" placeholder="Attach to Project">
            </form>
            <button class="button" disabled>Start Sketching</button>
        </div>
    </div>
</section>
<section >
    <h1> My Ideas </h1>
    <ul class="idea-list">
        {% for idea in ideas %}

        <li>
            <div class="idea-info idea-list-col">
                <a href="#"><h2>{{ idea.title }}</h2></a>
                <div>
                    <p>Contributors: {{ idea.contributors}}</p>
                </div>
            </div>
            <button class="button idea-list-col edit-button"> Edit</button>
            <a href="#" class="idea-list-col">Go to Sketchbook</a>
        </li>
        {% endfor %}

    </ul>
</section>
{% endblock %}

erehwon/erehwon/templates/profiles/my-projects.html
{% extends "dashboard-layout-w-map.html" %}

{% load static %}

{% block main %}
{% comment Mariza wants to keep myproject as useful for debugging . can just render dashboard-layout-w-map when happy to discard %}
<section >
    <h1> My Projects </h1>
    <ul class="idea-list">
        {% for project in projects %}
        <li>
            <div class="idea-info idea-list-col">
                <a href="/project/{{project.id}}"><h2>{{ project.title }}</h2></a>
                <div>
                    <p>Contributors: 20</p>
                </div>
            </div>
            <a href="#" class="idea-list-col">Add to map</a>
            <a href="#" class="idea-list-col">Remove from map</a>
        </li>
        {% endfor %}
    </ul>
</section>
{% endcomment %}

{% endblock %}

erehwon/erehwon/templates/profiles/project.html
{% extends "dashboard-layout.html" %}

{% load static %}

{% block main %}
<h1> Add/Edit project </h1>
  {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
  <div>
    <form action="" method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ new_project_form.as_p }}
      <input type="submit"  class="button" value="Submit" />
    </form>
  <div>
{% endblock %}